[workspace]
resolver = "3"
members = [
    "tulip_rs",
    "tulip_test",
    "tulip_rs_uniffi",
    "tulip_rs_uniffi/tulip_rs_uniffi_macros",
    "tulip_rs_diplomat",
    "tulip_rs_diplomat/tulip_rs_diplomat_gen",
]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"

[profile.bench]
opt-level = 3
lto = "fat"
codegen-units = 1


[profile.dev]
debug = true
opt-level = 0
lto = false
#codegen-units = 1
